; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-atom]
platform = espressif32@~5.0.0
board = m5stack-atom
framework = arduino
lib_deps = 
	m5stack/M5Atom@^0.1.2
	fastled/FastLED@^3.6.0
	https://github.com/m5stack/M5Unit-ExtEncoder.git
	robtillaart/TCA9548@^0.3.0
	robtillaart/RunningMedian@^0.3.9
	jonniezg/EWMA@^1.0.2
	;dfrobot/DFRobot_GP8XXX@^1.0.1
	https://github.com/Industrial-Shields/arduino-Modbus.git
	;https://github.com/m5stack/ArduinoRS485.git

monitor_speed = 19200
